# fly.toml file generated for captain-internal-certificate-ruby on 2023-04-18T16:01:34+07:00

app = "captain-internal-certificate-ruby"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
